name: Feature Branches & PR Opening Workflow
run-name: "Build and Test by @${{ github.actor }}"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

permissions: read-all

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -e .

      - name: Run unit tests
        run: python -m pytest tests/